### ISSUE TITLE
Q: How are you making small executables? 

### ISSUE THREAD

**Issue by beshralghalil** [MechTechnology/SmartStitch#20]
I am just wondering how are you making smaller executables than me, even though I am using your exact same Build.spec?

**Comment by MechTechnology** [comment]
Honestly I am not doing anything special, I am running it on windows machine with python 3.10 installed.

The only thing I think of is that I run my build through pipenv with `pipenv run build`, so it builds from a  virtual environment that only has the needed packages for the project, so maybe that.

Is the file size difference that big in your builds?

**Comment by beshralghalil** [comment]
I was getting 300 MB builds, However using upx solved it.
