### ISSUE TITLE
Stuck when try to combine 

### ISSUE THREAD

**Issue by sashakeista** [MechTechnology/SmartStitch#3]
Hello there, I'd like to tell you that I have an issue when I tried to combine chapters or a chapter from a particular plaform (L*****), smartstitch stuck and it won't goes up any higher. Can you fix this issue? Thank you

**Comment by pepijnmm** [comment]
can you give the images that have that problem? because for me it works.

**Comment by MechTechnology** [comment]
I feel bad for closing this, but since there is no response from the original poster in 22 days, there is not much I can do. I hope version 2.0, fixes some of the issue you are facing.
