### ISSUE TITLE
Upgrade your code

### ISSUE THREAD

**Issue by ByRemus** [MechTechnology/SmartStitch#30]
Hello, I have a similar code but the output looks different. the code crops the image only where there is a line of white or black pixels. please contact me, I am ready to provide you with my code to improve yours (if possible). i will be grateful for feedback
by.zolotukhin@gmail.com

**Comment by MechTechnology** [comment]
This is not exactly how open source contributions, I'm not doubting your work, but if you found a significant improvement to current code base you're more than welcome to create a PR with it.

nevertheless, the sensitivity adjustment is what allow the cropping to happen at a fully solid color line of pixel, or allow some gradient, with lower sensitivity allowing for more gradient to be allowed at the crop line.
